### ISSUE TITLE
[BUG] Numpy deprecation

### ISSUE THREAD

**Issue by robertdstein** [winter-telescope/winterdrp#285]
**Describe the bug**
We are stuck on our currently pinned numpy version, because of a new error that arises with more up to date numpy versions. See #283. This will presumably become an increasing barrier to adoption of any updates to numpy-dependent packages.

**To Reproduce**
Run CI with numpy:

```
Traceback (most recent call last):
  File "/home/runner/work/winterdrp/winterdrp/tests/test_errors.py", line 36, in test_pipeline
    _, errorstack = pipeline.reduce_images(
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/winterdrp/winterdrp/winterdrp/pipelines/base_pipeline.py", line 256, in reduce_images
    processors = self.set_configuration(configuration)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/winterdrp/winterdrp/winterdrp/pipelines/base_pipeline.py", line 185, in set_configuration
    processor.check_prerequisites()
  File "/home/runner/work/winterdrp/winterdrp/winterdrp/processors/database/base_database_processor.py", line 124, in check_prerequisites
    self.check_database_setup()
  File "/home/runner/work/winterdrp/winterdrp/winterdrp/processors/database/base_database_processor.py", line 163, in check_database_setup
    self.pg_user.create_tables_from_schema(self.schema_dir, self.db_name)
  File "/home/runner/work/winterdrp/winterdrp/winterdrp/processors/database/postgres.py", line 123, in create_tables_from_schema
    ordered_schema_files = get_ordered_schema_list(schema_files)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/winterdrp/winterdrp/winterdrp/processors/database/utils.py", line 61, in get_ordered_schema_list
    foreign_tables_list = get_foreign_tables_list(schema_files)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/winterdrp/winterdrp/winterdrp/processors/database/utils.py", line 50, in get_foreign_tables_list
    return np.array(foreign_tables_list)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (11,) + inhomogeneous part.
```

**Expected behaviour**
This should not happen. Let's fix the error.

**Comment by robertdstein** [comment]
Now fixed (or bypassed), since #283 passed tests.
